version: "3"

services:
  wp:
    image: wordpress
    volumes:
      - wordpress_data:/var/www/html
      - ./wp-config.php:/wp-config.php
    ports:
      - 8080:80

  db:
    image: mysql
    restart: always
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 6003
      MYSQL_DATABASE: wordpress

volumes:
  db_data:
  wordpress_data:
